[workspace]
authors = ["Paul Dutton <jodgey4@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "LeNet5Mojo"
platforms = ["linux-64"]
version = "0.2.0"

[tasks]
formatall = "mojo format *.mojo; mojo format cpu/*.mojo; mojo format accel/*.mojo"

#tests = { cmd = "mojo arena.mojo; mojo mylogger.mojo; mojo ops.mojo; mojo tokenizer/tokenchunks.mojo; mojo tokenizer/tests.mojo && rm temp.tok", cwd = "src" }
sanitize = { cmd = "mojo build -g2 -O1 --sanitize=address -Xlinker -lm main.mojo && ./main"}
cdebug = { cmd = "mojo build -g2 -O1 --debug-info-language=C -Xlinker -lm main.mojo"}
buildmain = { cmd = "mojo build -Xlinker -lm main.mojo", cwd = "src" }
#flamegraphs = { cmd = "./flamegraphing/graphmain.sh; ./flamegraphing/graphtokenizer.sh;", cwd = "src" }
nsysprofile = { cmd = "nsys profile --trace=nvtx,cuda --force-overwrite=true --output=basic mojo main.mojo && nsys stats --force-export=true basic.nsys-rep", cwd = "."}

[dependencies]
matplotlib = ">=3.10.9,<4"
numpy = ">=2.4.6,<3"
mojo = ">=1.0.0b2.dev2026052421,<2"
pandas = ">=3.0.3,<4"
cuda-toolkit = ">=13.2.1,<14"
