import std.os as os
from std.pathlib import Path
from std.memory import memcpy
from std.sys import size_of, stderr

from image import Image
from cpu.arena import CPUAllocator, CPUBumpArenaAllocator as Arena


# TODO: (future) if CPU hot path also moves off List[Image] AoS, both CPU and GPU can share these
# SoA spans directly. Image would become a lightweight view rather than an owned arena-backed struct.
@fieldwise_init
struct MNISTDataView[
    is_mutable: Bool,
    //,
    origin: Origin[mut = is_mutable],
](Sized, TrivialRegisterPassable):
    var raw_pixels: Span[UInt8, Self.origin]
    var raw_labels: Span[UInt8, Self.origin]

    # The two-span constructor is generated by @fieldwise_init:
    #   __init__(out self, raw_pixels: Span[UInt8, Self.origin],
    #            raw_labels: Span[UInt8, Self.origin])
    # so call sites that pass two same-origin spans bind to it directly.

    # Nice-to-have: pack a List[Image] into caller-supplied contiguous "arenas" supplied as Spans.
    # CANNOT take Some[CPUAllocator] — memory must be contiguous.
    def __init__[
        buf_origin: MutOrigin
    ](
        out self,
        images: List[Image],
        pixel_buffer: Span[UInt8, buf_origin],
        label_buffer: Span[UInt8, buf_origin],
    ) raises:
        comptime size = Image.PixelLayout.size()  # 784 raw bytes, NOT DataTensor (1024)
        var num_images = len(images)
        if pixel_buffer == label_buffer:
            raise Error("Buffers cannot be the same for MNISTDataView.")
        if len(pixel_buffer) < size * num_images:
            raise Error("Pixel buffer not large enough.")
        if len(label_buffer) < num_images:
            raise Error("Label buffer not large enough.")

        var offset = 0
        var pptr = pixel_buffer.unsafe_ptr()
        for i in range(num_images):
            var img = images[i]
            memcpy(src=img.pixels.ptr, dest=pptr + offset, count=size)
            label_buffer.unsafe_get(i) = img.label
            offset += size
        self.raw_pixels = rebind[Span[UInt8, Self.origin]](pixel_buffer)
        self.raw_labels = rebind[Span[UInt8, Self.origin]](label_buffer)

    def __len__(self) -> Int:
        return len(self.raw_labels)

    def __getitem__(
        self, start: Int, end: Int
    ) -> MNISTDataView[ImmutUntrackedOrigin]:
        # Read-only sub-view (slicing for inference). It can't tie to origin_of(self):
        # MNISTDataView is TrivialRegisterPassable, so `self` is a register value with
        # no memory origin (unlike the repo, which is why getTrainBatch/getTestBatch
        # can use origin_of(self)). And the abstract mutable Self.origin made the
        # exclusivity checker treat the disjoint pixel/label spans as aliasing. So the
        # sub-view is IMMUTABLE + untracked: immutable spans don't alias-conflict, and
        # untracked matches the project's hand-managed-lifetime approach.
        comptime image_size = Image.PixelLayout.size()
        var p_ptr = rebind[UnsafePointer[UInt8, ImmutUntrackedOrigin]](
            self.raw_pixels.unsafe_ptr() + start * image_size
        )
        var l_ptr = rebind[UnsafePointer[UInt8, ImmutUntrackedOrigin]](
            self.raw_labels.unsafe_ptr() + start
        )
        var pixels_span = Span(ptr=p_ptr, length=(end - start) * image_size)
        var labels_span = Span(ptr=l_ptr, length=(end - start))
        return MNISTDataView(pixels_span, labels_span)


struct MNISTDataRepository:
    comptime COUNT_TRAIN = 60000
    comptime COUNT_TEST = 10000

    var _train_pixels_arena: Arena
    var _test_pixels_arena: Arena
    var _train_labels_arena: Arena
    var _test_labels_arena: Arena
    var test_data: List[
        Image
    ]  # Image is a label + a (fat LayoutTensor) pointer into the arena for the pixels
    var train_data: List[Image]

    var data_dir: Path
    var train_image_file: Path
    var train_label_file: Path
    var test_image_file: Path
    var test_label_file: Path

    def __init__(out self, data_dir: String = "data") raises:
        # setup paths
        self.data_dir = Path(data_dir)
        self.train_image_file = Path(data_dir + "/train-images-idx3-ubyte")
        self.train_label_file = Path(data_dir + "/train-labels-idx1-ubyte")
        self.test_image_file = Path(data_dir + "/t10k-images-idx3-ubyte")
        self.test_label_file = Path(data_dir + "/t10k-labels-idx1-ubyte")

        # setup storage and do the loading
        comptime image_size_in_bytes = Image.PixelLayout.size()  # 784, not DataTensor (1024)
        self._train_pixels_arena = Arena(image_size_in_bytes * Self.COUNT_TRAIN)
        self._train_labels_arena = Arena(size_of[UInt8]() * Self.COUNT_TRAIN)
        self._test_pixels_arena = Arena(image_size_in_bytes * Self.COUNT_TEST)
        self._test_labels_arena = Arena(size_of[UInt8]() * Self.COUNT_TEST)
        self.test_data = List[Image](capacity=Self.COUNT_TEST)
        self.train_data = List[Image](capacity=Self.COUNT_TRAIN)
        # let read failures propagate — continuing with empty/partial datasets
        # just shows up later as a baffling "0/10000 correct"
        Self._readSplit(
            self.train_image_file,
            self.train_label_file,
            Self.COUNT_TRAIN,
            self._train_pixels_arena,
            self._train_labels_arena,
            self.train_data,
            "train",
        )
        Self._readSplit(
            self.test_image_file,
            self.test_label_file,
            Self.COUNT_TEST,
            self._test_pixels_arena,
            self._test_labels_arena,
            self.test_data,
            "test",
        )

    @staticmethod
    def _readSplit(
        image_file: Path,
        label_file: Path,
        count: Int,
        mut pixels_arena: Arena,
        mut labels_arena: Arena,
        mut data: List[Image],
        split: StaticString,
    ) raises:
        """Read `count` images + labels from the IDX files into the supplied
        pixel/label arenas and image list. Shared by the train and test loads —
        callers pass the matching destination fields (disjoint, so taking them
        as separate `mut` args avoids a whole-`self` borrow)."""
        comptime size = Image.PixelLayout.size()  # 784 bytes/image
        try:
            with open(image_file, "r") as data_file:
                with open(label_file, "r") as label_handle:
                    _ = data_file.seek(16, os.SEEK_SET)  # skip IDX image header
                    _ = label_handle.seek(8, os.SEEK_SET)  # skip IDX label header
                    for c in range(count):
                        var data_list = data_file.read_bytes(size)  # List[Byte]
                        var temp = label_handle.read_bytes(1)
                        var data_label: UInt8 = temp[0]

                        var img = Image(data_list, data_label, pixels_arena)
                        labels_arena.buffer[c] = data_label
                        data.append(img^)
        except e:
            raise Error(t"Error with input MNIST {split} binary files: {e}.")

    # TODO: consider combining into one method for test and train and use arg to pick
    def getTrainBatch(self, start: Int, end: Int) -> MNISTDataView[origin=origin_of(self)]:
        """Get a view / span / slice from the arena directly as raw Bytes."""
        if end <= start or end > Self.COUNT_TRAIN:
            print(
                t"getTrainBatch error: invalid slice {start}:{end}).",
                file=stderr,
            )
        comptime image_size_in_bytes = Image.PixelLayout.size()  # 784 bytes/image
        var p_ptr = rebind[UnsafePointer[UInt8, origin_of(self)]](
            self._train_pixels_arena.buffer + (start * image_size_in_bytes)
        )
        var l_ptr = rebind[UnsafePointer[UInt8, origin_of(self)]](
            self._train_labels_arena.buffer + start
        )
        var pixels_span = Span(ptr=p_ptr, length=(end - start) * image_size_in_bytes)
        var labels_span = Span(ptr=l_ptr, length=(end - start))
        return MNISTDataView(pixels_span, labels_span)

    def getTestBatch(self, start: Int, end: Int) -> MNISTDataView[origin=origin_of(self)]:
        """Get a view / span / slice from the arena directly as raw Bytes."""
        if end <= start or end > Self.COUNT_TEST:
            print(
                t"getTestBatch error: invalid slice {start}:{end}).",
                file=stderr,
            )
        comptime image_size_in_bytes = Image.PixelLayout.size()  # 784 bytes/image
        var p_ptr = rebind[UnsafePointer[UInt8, origin_of(self)]](
            self._test_pixels_arena.buffer + (start * image_size_in_bytes)
        )
        var l_ptr = rebind[UnsafePointer[UInt8, origin_of(self)]](
            self._test_labels_arena.buffer + start
        )
        var pixels_span = Span(ptr=p_ptr, length=(end - start) * image_size_in_bytes)
        var labels_span = Span(ptr=l_ptr, length=(end - start))
        return MNISTDataView(pixels_span, labels_span)

    # Shuffle helpers

    comptime seed_default = 69

    @staticmethod
    def _shuffleData(mut data: List[Image], seed: Int = Self.seed_default):
        """
        Not needed, but I / Claude wrote it just to play around and learn.
        """
        var count = len(data)
        if count < 1:
            return
        var rng_state = seed
        # some Claude 4 work
        for i in range(count - 1, 0, -1):
            rng_state = (rng_state * 1664525 + 1013904223) % 2147483647
            var j = Int(rng_state) % (i + 1)

            var temp = data[i]
            data[i] = data[j]
            data[j] = temp

    def shuffle(mut self, seed: Int = Self.seed_default):
        Self._shuffleData(self.train_data, seed)
        # Self.shuffleData(self.test_data, seed) # not sure why you'd want to
